language: go
go:
- '1.12'
- master
os:
- linux
- osx
install: true
env:
- GO111MODULE=on NAME=jki
script:
- go test -v -race ./...
cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$HOME/gopath/pkg/mod"
